<?php
namespace Aura\Sql;

/**
 * Test class for Gateway.
 * Generated by PHPUnit on 2012-09-27 at 23:05:43.
 */
class GatewayTest extends \PHPUnit_Framework_TestCase
{
    use Assertions;
    
    /**
     * @var Gateway
     */
    protected $gateway;

    protected $mapper;
    
    protected $connection;
    
    protected $connections;
    
    protected $default = [
        'connection' => 'sqlite',
        'dsn'        => ':memory:',
    ];
    
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
        $this->factory = new ConnectionFactory;
        $this->connections = new ConnectionLocator(
            $this->factory,
            $this->default,
            [],
            []
        );
        $this->mapper = new MockMapper;
        $this->gateway = new Gateway($this->connections, $this->mapper);
        
        $db_setup_class = 'Aura\Sql\DbSetup\Sqlite';
        $this->connection = $this->connections->getWrite();
        $db_setup = new DbSetup\Sqlite(
            $this->connection,
            $this->mapper->getTable(),
            'aura_test_schema1',
            'aura_test_schema2'
        );
        $db_setup->exec();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        parent::tearDown();
    }

    /**
     * @covers Aura\Sql\Gateway::getConnections
     * @todo Implement testGetConnections().
     */
    public function testGetConnections()
    {
        $actual = $this->gateway->getConnections();
        $this->assertSame($this->connections, $actual);
    }

    /**
     * @covers Aura\Sql\Gateway::getMapper
     * @todo Implement testGetMapper().
     */
    public function testGetMapper()
    {
        $actual = $this->gateway->getMapper();
        $this->assertSame($this->mapper, $actual);
    }

    /**
     * @covers Aura\Sql\Gateway::insert
     * @todo Implement testInsert().
     */
    public function testInsert()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Aura\Sql\Gateway::update
     * @todo Implement testUpdate().
     */
    public function testUpdate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Aura\Sql\Gateway::delete
     * @todo Implement testDelete().
     */
    public function testDelete()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Aura\Sql\Gateway::newSelect
     * @todo Implement testNewSelect().
     */
    public function testNewSelect()
    {
        $select = $this->gateway->newSelect();
        $connection = $select->getConnection();
        $this->assertSame($this->connection, $connection);
        $expect = '
            SELECT
                "aura_test_table"."id" AS "identity",
                "aura_test_table"."name" AS "firstName",
                "aura_test_table"."test_size_scale" AS "sizeScale",
                "aura_test_table"."test_default_null" AS "defaultNull",
                "aura_test_table"."test_default_string" AS "defaultString",
                "aura_test_table"."test_default_number" AS "defaultNumber",
                "aura_test_table"."test_default_ignore" AS "defaultIgnore"
            FROM
                "aura_test_table"
        ';
        $actual = (string) $select;
        $this->assertSameSql($expect, $actual);
    }

    /**
     * @covers Aura\Sql\Gateway::fetchAll
     * @todo Implement testFetchAll().
     */
    public function testFetchAll()
    {
        $select = $this->gateway->newSelect();
        $result = $this->gateway->fetchAll($select);
        $expect = 10;
        $actual = count($result);
        $this->assertEquals($expect, $actual);
    }

    /**
     * @covers Aura\Sql\Gateway::fetchCol
     * @todo Implement testFetchCol().
     */
    public function testFetchCol()
    {
        $select = $this->gateway->newSelect(['id'])->orderBy(['id']);
        $result = $this->connection->fetchCol($select);

        $expect = 10;
        $actual = count($result);
        $this->assertEquals($expect, $actual);
        
        // // 1-based IDs, not 0-based sequential values
        $expect = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'];
        $this->assertEquals($expect, $result);
    }

    /**
     * @covers Aura\Sql\Gateway::fetchOne
     * @todo Implement testFetchOne().
     */
    public function testFetchOne()
    {
        $select = $this->gateway->newSelect(['id', 'name'])->where('id = ?', 1);
        $actual = $this->gateway->fetchOne($select);
        $expect = (object) [
            'identity'  => '1',
            'firstName' => 'Anna',
        ];
        $this->assertEquals($expect, $actual);
    }

    /**
     * @covers Aura\Sql\Gateway::fetchPairs
     * @todo Implement testFetchPairs().
     */
    public function testFetchPairs()
    {
        $select = $this->gateway->newSelect(['id', 'name'])->orderBy(['id']);
        $actual = $this->connection->fetchPairs($select);
        $expect = [
          1  => 'Anna',
          2  => 'Betty',
          3  => 'Clara',
          4  => 'Donna',
          5  => 'Fiona',
          6  => 'Gertrude',
          7  => 'Hanna',
          8  => 'Ione',
          9  => 'Julia',
          10 => 'Kara',
        ];
        $this->assertEquals($expect, $actual);
    }

    /**
     * @covers Aura\Sql\Gateway::fetchValue
     * @todo Implement testFetchValue().
     */
    public function testFetchValue()
    {
        $select = $this->gateway->newSelect(['id'])->where('id = ?', 1);
        $actual = $this->connection->fetchValue($select);
        $expect = '1';
        $this->assertEquals($expect, $actual);
    }
}
