<?php
namespace Aura\Sql;

/**
 * Test class for Select.
 * Generated by PHPUnit on 2012-02-26 at 11:59:30.
 */
class SelectTest extends \PHPUnit_Framework_TestCase
{
    protected $select;

    protected $adapter;
    
    protected function setUp()
    {
        parent::setUp();
        $adapter_factory = new AdapterFactory;
        $this->adapter = $adapter_factory->newInstance('sqlite', ':memory:');
        $this->select = $this->adapter->newSelect();
    }
    
    protected function tearDown()
    {
        parent::tearDown();
    }

    protected function assertSameSql($expect, $actual)
    {
        $expect = trim($expect);
        $expect = preg_replace('/^\s*/m', '', $expect);
        $expect = preg_replace('/\s*$/m', '', $expect);
        
        $actual = trim($actual);
        $actual = preg_replace('/^\s*/m', '', $actual);
        $actual = preg_replace('/\s*$/m', '', $actual);
        
        $this->assertSame($expect, $actual);
    }
    
    public function testSetAndGetPaging()
    {
        $expect = 88;
        $this->select->setPaging($expect);
        $actual = $this->select->getPaging();
        $this->assertSame($expect, $actual);
    }

    public function testDistinct()
    {
        $this->select->distinct()
                     ->from('t1')
                     ->cols(['t1.c1', 't1.c2', 't1.c3']);
        
        $actual = $this->select->__toString();
        
        $expect = '
            SELECT DISTINCT
                "t1"."c1",
                "t1"."c2",
                "t1"."c3"
            FROM
                "t1"
        ';
        $this->assertSameSql($expect, $actual);
    }
    
    public function testCols()
    {
        $this->select->cols(['t1.c1', 'c2', 'COUNT(t1.c3)']);
        $actual = $this->select->__toString();
        $expect = '
            SELECT
                "t1"."c1",
                c2,
                COUNT("t1"."c3")
        ';
        $this->assertSameSql($expect, $actual);
    }
    
    public function testFrom()
    {
        $this->select->from('t1')
                     ->from('t2');
                     
        $actual = $this->select->__toString();
        $expect = '
            SELECT
            FROM
                "t1",
                "t2"
        ';
        $this->assertSameSql($expect, $actual);
    }
    
    public function testFromSubSelect()
    {
        $sub = "SELECT * FROM t2";
        $this->select->cols(['*'])->fromSubSelect($sub, "a2");
        $expect = '
            SELECT
                *
            FROM
                (SELECT * FROM t2) AS "a2"
        ';
        $actual = $this->select->__toString();
        $this->assertSameSql($expect, $actual);
    }
    
    public function testFromSubSelectObject()
    {
        $sub = $this->adapter->newSelect();
        $sub->cols(['*'])->from('t2');
        
        $this->select->cols(['*'])->fromSubSelect($sub, "a2");
        $expect = '
            SELECT
                *
            FROM
                (SELECT
                    *
                FROM
                    "t2"
                ) AS "a2"
        ';
        $actual = $this->select->__toString();
        $this->assertSameSql($expect, $actual);
    }
    
    public function testJoin()
    {
        $this->select->join("left", "t2", "t1.id = t2.id");
        $this->select->join("inner", "t3 AS a3", "t2.id = a3.id");
        $this->select->join("natural", "t4");
        $expect = '
            SELECT
            LEFT JOIN "t2" ON "t1"."id" = "t2"."id"
            INNER JOIN "t3" AS "a3" ON "t2"."id" = "a3"."id"
            NATURAL JOIN "t4"
        ';
        $actual = $this->select->__toString();
        $this->assertSameSql($expect, $actual);
    }
    
    public function testJoinSubSelect()
    {
        $sub1 = "SELECT * FROM t2";
        $sub2 = "SELECT * FROM t3";
        $this->select->joinSubSelect("left", $sub1, "a2", "t2.c1 = a3.c1");
        $this->select->joinSubSelect("natural", $sub2, "a3");
        $expect = '
            SELECT
            LEFT JOIN (SELECT * FROM t2) AS "a2" ON "t2"."c1" = "a3"."c1"
            NATURAL JOIN (SELECT * FROM t3) AS "a3"
        ';
        $actual = $this->select->__toString();
        $this->assertSameSql($expect, $actual);
    }
    
    public function testJoinSubSelectObject()
    {
        $sub = $this->adapter->newSelect();
        $sub->cols(['*'])->from('t2');
        
        $this->select->joinSubSelect("left", $sub, "a3", "t2.c1 = a3.c1");
        $expect = '
            SELECT
            LEFT JOIN (SELECT
                *
            FROM
                "t2"
            ) AS "a3" ON "t2"."c1" = "a3"."c1"
        ';
        $actual = $this->select->__toString();
        $this->assertSameSql($expect, $actual);
    }
    
    public function testWhere()
    {
        $this->select->where("c1 = c2")
                     ->where("c3 = ?", 'foo');
        $expect = '
            SELECT
            WHERE
                c1 = c2
                AND c3 = \'foo\'
        ';
        
        $actual = $this->select->__toString();
        $this->assertSameSql($expect, $actual);
    }
    
    public function testOrWhere()
    {
        $this->select->orWhere("c1 = c2")
                     ->orWhere("c3 = ?", 'foo');
        
        $expect = '
            SELECT
            WHERE
                c1 = c2
                OR c3 = \'foo\'
        ';
        
        $actual = $this->select->__toString();
        $this->assertSameSql($expect, $actual);
    }
    
    public function testGroupBy()
    {
        $this->select->groupBy(['c1', 't2.c2']);
        $expect = '
            SELECT
            GROUP BY
                c1,
                "t2"."c2"
        ';
        
        $actual = $this->select->__toString();
        $this->assertSameSql($expect, $actual);
    }
    
    public function testHaving()
    {
        $this->select->having("c1 = c2")
                     ->having("c3 = ?", 'foo');
        $expect = '
            SELECT
            HAVING
                c1 = c2
                AND c3 = \'foo\'
        ';
        
        $actual = $this->select->__toString();
        $this->assertSameSql($expect, $actual);
    }
    
    public function testOrHaving()
    {
        $this->select->orHaving("c1 = c2")
                     ->orHaving("c3 = ?", 'foo');
        $expect = '
            SELECT
            HAVING
                c1 = c2
                OR c3 = \'foo\'
        ';
        
        $actual = $this->select->__toString();
        $this->assertSameSql($expect, $actual);
    }
    
    public function testOrderBy()
    {
        $this->select->orderBy(['c1', 'UPPER(t2.c2)', ]);
        $expect = '
            SELECT
            ORDER BY
                c1,
                UPPER("t2"."c2")
        ';
        
        $actual = $this->select->__toString();
        $this->assertSameSql($expect, $actual);
    }
    
    public function testLimit()
    {
        $this->select->limit(10);
        $expect = '
            SELECT
            LIMIT 10
        ';
        $actual = $this->select->__toString();
        $this->assertSameSql($expect, $actual);
    }
    
    public function testOffset()
    {
        $this->select->offset(40);
        $expect = '
            SELECT
            OFFSET 40
        ';
        $actual = $this->select->__toString();
        $this->assertSameSql($expect, $actual);
    }
    
    public function testPage()
    {
        $this->select->page(5);
        $expect = '
            SELECT
            LIMIT 10 OFFSET 40
        ';
        $actual = $this->select->__toString();
        $this->assertSameSql($expect, $actual);
    }
    
    public function testForUpdate()
    {
        $this->select->forUpdate();
        $expect = '
            SELECT
            FOR UPDATE
        ';
        $actual = $this->select->__toString();
        $this->assertSameSql($expect, $actual);
    }
    
    public function testUnion()
    {
        $this->select->cols(['c1'])
                     ->from('t1')
                     ->union()
                     ->cols(['c2'])
                     ->from('t2');
        $expect = '
            SELECT
                c1
            FROM
                "t1"
            UNION
            SELECT
                c2
            FROM
                "t2"
        ';
        
        $actual = $this->select->__toString();
        $this->assertSameSql($expect, $actual);
    }
    
    public function testUnionAll()
    {
        $this->select->cols(['c1'])
                     ->from('t1')
                     ->unionAll()
                     ->cols(['c2'])
                     ->from('t2');
        $expect = '
            SELECT
                c1
            FROM
                "t1"
            UNION ALL
            SELECT
                c2
            FROM
                "t2"
        ';
        
        $actual = $this->select->__toString();
        $this->assertSameSql($expect, $actual);
    }
}
