build:
    image: default-bionic
    nodes:
        analysis:
            environment:
                php: 8.4.0
            packages:
                - openssl=1.1.*
            tests:
                override:
                    - php-scrutinizer-run
filter:
    paths: ["src/*"]
