build:
    dependencies:
        before_install:
          - sudo apt-get update
          - sudo apt-get install -y openssl libssl-dev
    image: default-bionic
    environment:
        php: 
            version: 8.4.0
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
filter:
    paths: 
        - "src/*"
