<?php
namespace Aura\Sql\Connection;
use PDO;
use Aura\Sql\Select;

/**
 * Test class for MssqlDblib.
 * Generated by PHPUnit on 2011-06-21 at 16:50:02.
 */
class SqlsrvDenaliTest extends SqlsrvTest
{
    protected $connect_type = 'sqlsrv_denali';
    
    protected $connect_params = array(
        'dsn' => array(
            'Server' => 'jic-31.jic',
            'Database' => 'ZF',
        ),
        'username' => 'sa',
        'password' => 'JIC2011@MS',
        'options' =>  array(),
    );
    
    protected $expect_class = 'Aura\Sql\Connection\SqlsrvDenali';
    
    protected $expect_dsn_string = 'sqlsrv:Server=jic-31.jic;Database=ZF';
    
    public function testFetchTableList()
    {
        $actual = $this->conn->fetchTableList();
        $expect = array('artist', 'aura');
        $this->assertSame($expect, $actual);
    }
    
    public function testConvertSelect()
    {
        $select = new Select;
        $select->distinct = true;
        $select->cols[] = 'id';
        $select->cols[] = 'name';
        $select->from[] = 'aura';
        $select->limit = 5;
        $select->offset = 5;
        $select->order[] = 'name';
        
        $actual = $this->conn->fetchAll($select);
        $expect = array (
            0 => array (
                'id' => '6',
                'name' => 'Gertrude',
            ),
            1 => array (
                'id' => '7',
                'name' => 'Hanna',
            ),
            2 => array (
                'id' => '8',
                'name' => 'Ione',
            ), 3 => 
            array (
                'id' => '9',
                'name' => 'Julia',
            ), 4 => 
            array (
                'id' => '10',
                'name' => 'Kara',
            ),
        );
        
        $this->assertSame($expect, $actual);
    }
}
