<?php
namespace Aura\Sql\Driver;
use PDO;

/**
 * Test class for AbstractDriver.
 * Generated by PHPUnit on 2011-06-21 at 16:49:51.
 */
abstract class AbstractDriverTest extends \PHPUnit_Framework_TestCase
{
    protected $extension;
    
    protected $dsn = [];
    
    protected $connect_params = array(
        'dsn'      => [],
        'username' => null,
        'password' => null,
        'options'  => [],
    );
    
    protected $expect_dsn_string;
    
    protected $driver_class;
    
    protected $conn;
    
    protected $schema1 = 'aura_test_schema1';
    
    protected $schema2 = 'aura_test_schema2';
    
    protected $table = 'aura_test_table';
    
    protected $create_table;
    
    protected $expect_fetch_table_list = ['aura_test_table'];
    
    protected $expect_fetch_table_cols;
    
    protected $expect_quote_scalar;
    
    protected $expect_quote_array;
    
    protected $expect_quote_into;
    
    protected $expect_quote_into_many;
    
    protected $expect_quote_multi;
    
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
        parent::setUp();
        
        // skip if we don't have the extension
        if (! extension_loaded($this->extension)) {
            $this->markTestSkipped("Extension '{$this->extension}' not loaded.");
        }
        
        // load test config values
        $test_class = get_class($this);
        $this->connect_params = array_merge(
            $this->connect_params,
            $GLOBALS[$test_class]['connect_params']
        );
        
        $this->expect_dsn_string = $GLOBALS[$test_class]['expect_dsn_string'];
        
        $params = $this->connect_params;
        $class  = $this->driver_class;
        
        $this->conn = new $class(
            $params['dsn'],
            $params['username'],
            $params['password'],
            $params['options']
        );
        
        $this->dropSchemas();
        $this->createSchemas();
        $this->createTables();
        $this->fillTable();
    }
    
    abstract protected function createSchemas();
    
    abstract protected function dropSchemas();
    
    protected function createTables()
    {
        // create in schema 1
        $sql = $this->create_table;
        $this->conn->query($sql);
        
        // create again in schema 2
        $sql = str_replace($this->table, "{$this->schema2}.{$this->table}", $sql);
        $this->conn->query($sql);
    }
    
    // only fills in schema 1
    protected function fillTable()
    {
        $names = [
            'Anna', 'Betty', 'Clara', 'Donna', 'Fiona',
            'Gertrude', 'Hanna', 'Ione', 'Julia', 'Kara',
        ];
        
        foreach ($names as $name) {
            $this->conn->insert($this->table, ['name' => $name]);
        }
    }
    
    /**
     * @todo Implement testGetDsnString().
     */
    public function testGetDsnString()
    {
        $actual = $this->conn->getDsnString();
        $this->assertSame($this->expect_dsn_string, $actual);
    }
    
    /**
     * @todo Implement testConnect().
     */
    public function testGetPdo()
    {
        $actual = $this->conn->getPdo();
        $this->assertInstanceOf('\PDO', $actual);
    }
    
    public function testQuery()
    {
        $text = "SELECT * FROM {$this->table}";
        $stmt = $this->conn->query($text);
        $this->assertInstanceOf('PDOStatement', $stmt);
        $result = $stmt->fetchAll(PDO::FETCH_ASSOC);
        $expect = 10;
        $actual = count($result);
        $this->assertSame($expect, $actual);
    }
    
    public function testQueryWithData()
    {
        $text = "SELECT * FROM {$this->table} WHERE id <= :val";
        $data['val'] = '5';
        $stmt = $this->conn->query($text, $data);
        $this->assertInstanceOf('PDOStatement', $stmt);
        $result = $stmt->fetchAll(PDO::FETCH_ASSOC);
        $expect = 5;
        $actual = count($result);
        $this->assertSame($expect, $actual);
    }
    
    public function testFetchAll()
    {
        $text = "SELECT * FROM {$this->table}";
        $result = $this->conn->fetchAll($text);
        $expect = 10;
        $actual = count($result);
        $this->assertSame($expect, $actual);
    }
    
    public function testFetchAssoc()
    {
        $text = "SELECT * FROM {$this->table} ORDER BY id";
        $result = $this->conn->fetchAssoc($text);
        $expect = 10;
        $actual = count($result);
        $this->assertSame($expect, $actual);
        
        // // 1-based IDs, not 0-based sequential values
        $expect = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
        $actual = array_keys($result);
        $this->assertSame($expect, $actual);
    }
    
    public function testFetchCol()
    {
        $text = "SELECT id FROM {$this->table} ORDER BY id";
        $result = $this->conn->fetchCol($text);
        $expect = 10;
        $actual = count($result);
        $this->assertSame($expect, $actual);
        
        // // 1-based IDs, not 0-based sequential values
        $expect = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'];
        $this->assertSame($expect, $result);
    }
    
    public function testFetchValue()
    {
        $text = "SELECT id FROM {$this->table} WHERE id = 1";
        $actual = $this->conn->fetchValue($text);
        $expect = '1';
        $this->assertSame($expect, $actual);
    }
    
    public function testFetchPairs()
    {
        $text = "SELECT id, name FROM {$this->table} ORDER BY id";
        $actual = $this->conn->fetchPairs($text);
        $expect = [
          1  => 'Anna',
          2  => 'Betty',
          3  => 'Clara',
          4  => 'Donna',
          5  => 'Fiona',
          6  => 'Gertrude',
          7  => 'Hanna',
          8  => 'Ione',
          9  => 'Julia',
          10 => 'Kara',
        ];
        $this->assertSame($expect, $actual);
    }
    
    public function testFetchOne()
    {
        $text = "SELECT id, name FROM {$this->table} WHERE id = 1";
        $actual = $this->conn->fetchOne($text);
        $expect = [
            'id'   => '1',
            'name' => 'Anna',
        ];
        $this->assertSame($expect, $actual);
    }
    
    public function testFetchTableList()
    {
        $actual = $this->conn->fetchTableList();
        $this->assertSame($this->expect_fetch_table_list, $actual);
    }
    
    public function testFetchTableList_schema()
    {
        $actual = $this->conn->fetchTableList('aura_test_schema2');
        $this->assertSame($this->expect_fetch_table_list, $actual);
    }
    
    public function testFetchTableCols()
    {
        $actual = $this->conn->fetchTableCols($this->table);
        $this->assertSame($this->expect_fetch_table_cols, $actual);
    }
    
    public function testFetchTableCols_schema()
    {
        $actual = $this->conn->fetchTableCols($this->table, 'aura_test_schema2');
        $this->assertSame($this->expect_fetch_table_cols, $actual);
    }
    
    public function testQuote()
    {
        // quote a scalar
        $actual = $this->conn->quote('"foo" bar \'baz\'');
        $this->assertEquals($this->expect_quote_scalar, $actual);
        
        // quote a number
        $actual = $this->conn->quote(123.456);
        $this->assertEquals(123.456, $actual);
        
        // quote a numeric
        $actual = $this->conn->quote('123.456');
        $this->assertEquals(123.456, $actual);
        
        // quote an array
        $actual = $this->conn->quote(array('"foo"', 'bar', "'baz'"));
        $this->assertEquals($this->expect_quote_array, $actual);
    }
    
    /**
     * @todo Implement testQuoteInto().
     */
    public function testQuoteInto()
    {
        // no placeholders
        $actual = $this->conn->quoteInto('foo = bar', "'zim'");
        $expect = 'foo = bar';
        $this->assertEquals($expect, $actual);
        
        // one placeholder, one value
        $actual = $this->conn->quoteInto("foo = ?", "'bar'");
        $this->assertEquals($this->expect_quote_into,$actual);
        
        // many placeholders, many values
        $actual = $this->conn->quoteInto("foo = ? AND zim = ?", ["'bar'", "'baz'"]);
        $this->assertEquals($this->expect_quote_into_many, $actual);
        
        // many placeholders, too many values
        $actual = $this->conn->quoteInto("foo = ? AND zim = ?", ["'bar'", "'baz'", "'gir'"]);
        $this->assertEquals($this->expect_quote_into_many, $actual);
    }
    
    /**
     * @todo Implement testQuoteMulti().
     */
    public function testQuoteMulti()
    {
        $where = array(
            'id = 1',
            'foo = ?' => 'bar',
            'zim IN(?)' => array('dib', 'gir', 'baz'),
        );
        $actual = $this->conn->quoteMulti($where, ' AND ');
        $this->assertEquals($this->expect_quote_multi, $actual);
    }
    
    /**
     * @todo Implement testQuoteName().
     */
    public function testQuoteName()
    {
        // table AS alias
        $actual = $this->conn->quoteName('table AS alias');
        $this->assertSame($this->expect_quote_name_table_as_alias, $actual);
        
        // table.col AS alias
        $actual = $this->conn->quoteName('table.col AS alias');
        $this->assertSame($this->expect_quote_name_table_col_as_alias, $actual);
        
        // table alias
        $actual = $this->conn->quoteName('table alias');
        $this->assertSame($this->expect_quote_name_table_alias, $actual);
        
        // table.col alias
        $actual = $this->conn->quoteName('table.col alias');
        $this->assertSame($this->expect_quote_name_table_col_alias, $actual);
        
        // plain old identifier
        $actual = $this->conn->quoteName('table');
        $this->assertSame($this->expect_quote_name_plain, $actual);
        
        // star
        $actual = $this->conn->quoteName('*');
        $this->assertSame('*', $actual);
        
        // star dot star
        $actual = $this->conn->quoteName('*.*');
        $this->assertSame('*.*', $actual);
    }
    
    /**
     * @todo Implement testQuoteNamesIn().
     */
    public function testQuoteNamesIn()
    {
        $sql = "*, *.*, foo.bar, CONCAT('foo.bar', \"baz.dib\") AS zim";
        $actual = $this->conn->quoteNamesIn($sql);
        $this->assertSame($this->expect_quote_names_in, $actual);
    }
    
    public function testInsertAndLastInsertId()
    {
        $data = ['name' => 'Laura'];
        $actual = $this->conn->insert($this->table, $data);
        
        // did we get the right last ID?
        $actual = $this->conn->lastInsertId();
        $expect = '11';
        $this->assertSame($expect, $actual);
        
        // did it insert?
        $actual = $this->conn->fetchOne("SELECT id, name FROM {$this->table} WHERE id = 11");
        $expect = ['id' => '11', 'name' => 'Laura'];
        $this->assertSame($actual, $expect);
    }
    
    public function testUpdate()
    {
        $where = 'id = 1';
        $data  = ['name' => 'Annabelle'];
        $actual = $this->conn->update($this->table, $data, $where);
        
        // did it update?
        $actual = $this->conn->fetchOne("SELECT id, name FROM {$this->table} WHERE id = 1");
        $expect = ['id' => '1', 'name' => 'Annabelle'];
        $this->assertSame($actual, $expect);
        
        // did anything else update?
        $actual = $this->conn->fetchOne("SELECT id, name FROM {$this->table} WHERE id = 2");
        $expect = ['id' => '2', 'name' => 'Betty'];
        $this->assertSame($actual, $expect);
    }
    
    public function testDelete()
    {
        $where = 'id = 1';
        $actual = $this->conn->delete($this->table, $where);
        
        // did it delete?
        $actual = $this->conn->fetchOne("SELECT * FROM {$this->table} WHERE id = 1");
        $this->assertFalse($actual);
        
        // do we still have everything else?
        $actual = $this->conn->fetchAll("SELECT * FROM {$this->table}");
        $expect = 9;
        $this->assertSame($expect, count($actual));
    }
}
