<?php
namespace Aura\Sql;

/**
 * Test class for GatewayLocator.
 * Generated by PHPUnit on 2012-09-27 at 23:05:48.
 */
class GatewayLocatorTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var GatewayLocator
     */
    protected $gateways;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
        $registry = [
            'posts' => function() {
                $gateway = (object) ['type' => 'post'];
                return $gateway;
            },
            'comments' => function() {
                $gateway = (object) ['type' => 'comment'];
                return $gateway;
            },
            'authors' => function() {
                $gateway = (object) ['type' => 'author'];
                return $gateway;
            },
        ];
        
        $this->gateways = new GatewayLocator($registry);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        parent::tearDown();
    }

    /**
     * @covers Aura\Sql\GatewayLocator::set
     * @todo Implement testSet().
     */
    public function testSetAndGet()
    {
        $this->gateways->set('tags', function () {
            $gateway = (object) ['type' => 'tag'];
            return $gateway;
        });
        
        $gateway = $this->gateways->get('tags');
        $this->assertTrue($gateway->type == 'tag');
    }

    public function testGet_noSuchGateway()
    {
        $this->setExpectedException('Aura\Sql\Exception\NoSuchGateway');
        $gateway = $this->gateways->get('no-such-gateway');
    }
    
    public function test_iterator()
    {
        $expect = ['post', 'comment', 'author'];
        foreach ($this->gateways as $gateway) {
            $actual[] = $gateway->type;
        }
        $this->assertSame($expect, $actual);
    }
}
