<?php
namespace Aura\Sql\Connection;
use PDO;
use Aura\Sql\Select;

/**
 * Test class for MssqlDblib.
 * Generated by PHPUnit on 2011-06-21 at 16:50:02.
 */
class SqlsrvDenaliTest extends SqlsrvTest
{
    protected $connect_type = 'sqlsrv_denali';
    
    protected $connection_class = 'Aura\Sql\Connection\SqlsrvDenali';
    
    public function testFetchTableList()
    {
        $actual = $this->conn->fetchTableList();
        $expect = ['artist', 'aura'];
        $this->assertSame($expect, $actual);
    }
    
    public function testConvertSelect()
    {
        $select = new Select;
        $select->distinct = true;
        $select->cols[] = 'id';
        $select->cols[] = 'name';
        $select->from[] = 'aura';
        $select->limit = 5;
        $select->offset = 5;
        $select->order[] = 'name';
        
        $actual = $this->conn->fetchAll($select);
        $expect = [
            0 => [
                'id' => '6',
                'name' => 'Gertrude',
            ],
            1 => [
                'id' => '7',
                'name' => 'Hanna',
            ],
            2 => [
                'id' => '8',
                'name' => 'Ione',
            ], 3 => 
            [
                'id' => '9',
                'name' => 'Julia',
            ], 4 => 
            [
                'id' => '10',
                'name' => 'Kara',
            ],
        ];
        
        $this->assertSame($expect, $actual);
    }
}
