<?php
namespace Aura\Sql\Connection;

/**
 * Test class for MssqlDblib.
 * Generated by PHPUnit on 2011-06-21 at 16:50:02.
 */
class SqlsrvTest extends AbstractConnectionTest
{
    protected $extension = 'sqlsrv';
    
    protected $connect_type = 'sqlsrv';
    
    protected $connection_class = 'Aura\Sql\Connection\Sqlsrv';
    
    protected $create_table = "CREATE TABLE aura (
        id int IDENTITY NOT NULL,
        name NVARCHAR(50),
        PRIMARY KEY (id)
    )";
        
    protected $expect_convert_select = [
        0 => [
            'id' => '6',
            'name' => 'Gertrude',
            '__rownum__' => '6',
        ],
        1 => [
            'id' => '7',
            'name' => 'Hanna',
            '__rownum__' => '7',
        ],
        2 => [
            'id' => '8',
            'name' => 'Ione',
            '__rownum__' => '8',
        ],
        3 => 
        [
            'id' => '9',
            'name' => 'Julia',
            '__rownum__' => '9',
        ],
        4 => 
        [
            'id' => '10',
            'name' => 'Kara',
            '__rownum__' => '10',
        ],
    ];
    
    protected $expect_fetch_table_cols = [
        'id' => [
            'name' => 'id',
            'type' => 'int',
            'size' => '10',
            'scale' => NULL,
            'default' => NULL,
            'notnull' => true,
            'primary' => true,
            'autoinc' => true,
        ],
        'name' => [
            'name' => 'name',
            'type' => 'nvarchar',
            'size' => '50',
            'scale' => NULL,
            'default' => NULL,
            'notnull' => false,
            'primary' => false,
            'autoinc' => false,
        ],
    ];

}
